### ISSUE TITLE
add a comment section giscus

### ISSUE THREAD

**Issue by Tudyx** [nikomatsakis/babysteps#23]
I really like your blog content, I think being able to comment/react  posts would make it even better.

Adding a comment section with giscus, as described by [this comment on mdbook](https://github.com/rust-lang/mdBook/issues/99#issuecomment-1466165218) could be a nice addition.

By the way, as you are asking for help to refactor the blog, I think converting the whole thing to a tuned mdbook shouldn't be that hard. It will do the better mobile integration, syntax highlighting and CI/CD for free.

**Comment by nikomatsakis** [comment]
Interesting thought to use mdbook, that hadn't occurred to me :) I'm ok with hugo for now, I think.

**Comment by nikomatsakis** [comment]
Re: comments, I am torn. I turned them off some time back because I didn't have time to monitor, mediate, and respond to them, and I think I would like to keep it that way, even though I really appreciate hearing from people. This is why I sometimes create threads on internals or other places to drive feedback.
